[pytest]
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: Маркировка для смоук тестов
    regression: Маркировка для регрессионных тестов
    registration: Маркировка для регистрационных тестов
    autorization: Маркировка для тестов авторизации
    courses: Маркировка для тестов, связанных с курсами